#!/bin/bash -

sysfs_opts=nodev,noexec,nosuid
mount -n -t sysfs -o ${sysfs_opts} sysfs /sys
mount -t proc proc /proc
mount -t tmpfs tmpfs /tmp
echo "ls /tmp"
ls /tmp
# echo "rm -rf /tmp/my_db"
# rm -rf /tmp/my_db
pushd /aspen-gem5
./scripts/setup_machine.sh
popd
mkdir /mnt/huge
mount -t hugetlbfs pagesize=2MB /mnt/huge
echo 512 > /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
/sbin/m5 readfile > /tmp/script
chmod 755 /tmp/script
if [ -s /tmp/script  ]
then
    # If there is a script, execute the script and then exit the simulation
    su root -c '/tmp/script' # gives script full privileges as root user in multi-user mode
    sync
    sleep 10
    /sbin/m5 exit
fi
echo "No script found"